apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-sp-validator-tls
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-tls
  duration: 8760h
  renewBefore: 72h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
