apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: linkerd-proxy-injector-webhook-config
  annotations:
    cert-manager.io/inject-ca-from: linkerd/linkerd-proxy-injector-tls
