apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: linkerd-sp-validator-webhook-config
  annotations:
    cert-manager.io/inject-ca-from: linkerd/linkerd-sp-validator-tls
